
  CREATE TABLE DMI_COREP_RECAP_AGGR_MAIN
   (	AGGREGATION_MAIN NUMBER(12,0),
	ALLOCATED_LIMIT_AMT NUMBER(22,2),
	ALLOCATED_OUTSTANDING_AMT NUMBER(22,2),
	ECA_INDICATOR NUMBER(1,0)
   )
   PCTFREE 25
  PARTITION BY RANGE (RECORD_VALID_FROM)
  SUBPARTITION BY LIST (SYSTEM_ID)
 (
  PARTITION P_PRE2006  VALUES LESS THAN (TO_DATE('2006-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  TABLESPACE VORTEX_BUSS_DATA
 COMPRESS FOR ARCHIVE HIGH
 (
 SUBPARTITION P_PRE2006_AML  VALUES ('AML')  TABLESPACE VORTEX_BUSS_DATA
 COMPRESS FOR ARCHIVE HIGH ,
  SUBPARTITION P_PRE2006_BMG  VALUES ('BMG')  TABLESPACE VORTEX_BUSS_DATA
 COMPRESS FOR ARCHIVE HIGH
  SUBPARTITION P_PRE2006_DEFAULT  VALUES (DEFAULT)
  TABLESPACE VORTEX_BUSS_DATA
 COMPRESS FOR ARCHIVE HIGH
 ) ,
 PARTITION P_200601  VALUES LESS THAN (TO_DATE('2006-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  TABLESPACE VORTEX_BUSS_DATA_2006
 COMPRESS FOR ARCHIVE HIGH
 (
 SUBPARTITION P_200601_AML  VALUES ('AML')  TABLESPACE VORTEX_BUSS_DATA_2006
 COMPRESS FOR ARCHIVE HIGH ,
  SUBPARTITION P_200601_BMG  VALUES ('BMG')  TABLESPACE VORTEX_BUSS_DATA_2006
 COMPRESS FOR ARCHIVE HIGH ,
  SUBPARTITION P_200601_DEFAULT  VALUES (DEFAULT)
  TABLESPACE VORTEX_BUSS_DATA_2006
 COMPRESS FOR ARCHIVE HIGH
 ) ,
 PARTITION P_202103  VALUES LESS THAN (TO_DATE('2021-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
  TABLESPACE VORTEX_BUSS_DATA_2021
 COMPRESS FOR QUERY LOW
 (
 SUBPARTITION P_202103_AML  VALUES ('AML') SEGMENT CREATION IMMEDIATE
  TABLESPACE VORTEX_BUSS_DATA_2021
 COMPRESS FOR QUERY LOW ,
  SUBPARTITION P_202103_BMG  VALUES ('BMG') SEGMENT CREATION IMMEDIATE
  TABLESPACE VORTEX_BUSS_DATA_2021
    SUBPARTITION P_202103_DEFAULT  VALUES (DEFAULT)
  TABLESPACE VORTEX_BUSS_DATA_2021
 COMPRESS FOR QUERY LOW
 ) ,
 PARTITION P_999999  VALUES LESS THAN (MAXVALUE)
  TABLESPACE VORTEX_BUSS_DATA_9999
 COMPRESS FOR ARCHIVE HIGH
 (
 SUBPARTITION P_999999_AML  VALUES ('AML')  TABLESPACE VORTEX_BUSS_DATA_9999
 COMPRESS FOR ARCHIVE HIGH ,
  SUBPARTITION P_999999_BMG  VALUES ('BMG')  TABLESPACE VORTEX_BUSS_DATA_9999
 COMPRESS FOR ARCHIVE HIGH ,
  SUBPARTITION P_999999_DEFAULT  VALUES (DEFAULT)
  TABLESPACE VORTEX_BUSS_DATA_9999
 COMPRESS FOR ARCHIVE HIGH )
 )  ENABLE ROW MOVEMENT ;

